Anpassung Linter

diff --git a/test_it b/test_it
--- a/test_it
+++ b/test_it
@@ -2,15 +2,12 @@
 
 echo "=> Linting Ansible Code"
 fail_ansible=0
-for f in `find . -name "*.yml"`; do
-    echo "==> LINTING $f"
-    ansible-lint $f
-    rc=$?
-    if [[ $rc != 0 ]]; then
-        echo "==> LINTING FAIL: $f"
-        fail_ansible=1
-    fi
-done
+ansible-lint
+rc=$?
+if [[ $rc != 0 ]]; then
+  echo "==> LINTING FAIL: $f"
+  fail_ansible=1
+fi
 
 echo "=> Run Ansible"
 fail_provision=0
